## Looking into COVID-19 APIs

In [2]:
import requests
import os
from dotenv import load_dotenv, find_dotenv
from ast import literal_eval
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
if "jms_style_sheet" in plt.style.available:
    plt.style.use("jms_style_sheet")

In [4]:
url = "https://covid-19-data.p.rapidapi.com/report/country/all"

querystring = {"date":"2020-04-01"}

headers = {
    'x-rapidapi-host': "covid-19-data.p.rapidapi.com",
    'x-rapidapi-key': os.getenv("RAPID_API_KEY")
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":403,"detail":"Forbidden"}

In [22]:
url = "https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/covid-ovid-data/sixmonth/USA"

headers = {
    'x-rapidapi-host': "vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com",
    'x-rapidapi-key': os.getenv("RAPID_API_KEY")
    }

response = requests.request("GET", url, headers=headers)

# print(response.text)

In [23]:
df = pd.DataFrame(literal_eval(response.text))

In [24]:
df

,id,symbol,Country,Continent,date,total_cases,new_cases,total_deaths,new_deaths,total_tests,new_tests
0,22f61916-1ad8-418e-83cd-d1ab0b127671,USA,United States,North America,2021-12-22,51545991,238378,812069,2024,0,0
1,72ebc9c3-b407-4796-8189-94a046744967,USA,United States,North America,2021-12-21,51307613,178290,810045,2093,0,0
2,890dd4f1-56da-4e77-81dd-152b73748dc6,USA,United States,North America,2021-12-20,51129323,255061,807952,1513,0,0
3,b862ddee-ab2f-45cb-a000-d306084a4648,USA,United States,North America,2021-12-19,50874262,73184,806439,137,0,0
4,342bbeaf-451f-4df3-83d0-f52dc5e96529,USA,United States,North America,2021-12-18,50801078,73605,806302,479,0,0
...,...,...,...,...,...,...,...,...,...,...,...
168,fe422e1f-dee3-4bd3-9516-ffcc3ef0f9b1,USA,United States,North America,2021-07-07,33852894,22634,605845,321,475096541,776941
169,f80bc5a7-9b7b-4745-b322-a816a26c9b77,USA,United States,North America,2021-07-06,33830260,23411,605524,313,474319600,590113
170,c13fd644-b453-46b0-a292-862b490edcaa,USA,United States,North America,2021-07-05,33806849,8835,605211,122,473729487,306362
171,2fbcb087-9dea-4498-8800-1eb80d7bbbfe,USA,United States,North America,2021-07-04,33798014,3824,605089,38,473423125,259860
172,b96a48fe-1803-4c8a-ab29-a780af8fd006,USA,United States,North America,2021-07-03,33794190,4713,605051,82,473163265,445919